# Automated build at https://registry.hub.docker.com/u/konstruktoid/cleanbits/

FROM debian:wheezy

ADD https://raw.githubusercontent.com/konstruktoid/Docker/master/Security/cleanBits.sh /tmp/cleanBits.sh

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get -y clean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/lists/*

RUN \
  useradd --system --no-create-home --user-group --shell /bin/false dockeru && \
  /bin/bash /tmp/cleanBits.sh

ENTRYPOINT ["/bin/bash"]
CMD []
